name: Compile LaTeX and Create Release

on:
  push:
    branches: [ master ]  

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex  # Replace with your main .tex file name
          latexmk_use_xelatex: true

      - name: Check for PDF
        run: |
          if [ -f "main.pdf" ]; then
            echo "PDF file found"
          else
            echo "PDF file not found"
            exit 1
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: main.pdf

  create_release:
    needs: compile_latex
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d/%m/%y-%s')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  upload_asset:
    needs: [compile_latex, create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: Pushpinder_Resume.pdf
          asset_content_type: application/pdf

  deploy_to_github_pages:
    needs: compile_latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy generated PDF to deployment directory
        run: |
          mkdir -p out
          cp main.pdf out/Pushpinder_Resume.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
